/****************************************************************************
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2023 VeriSilicon Holdings Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *****************************************************************************
 *
 * The GPL License (GPL)
 *
 * Copyright (c) 2023 VeriSilicon Holdings Co., Ltd.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program;
 *
 *****************************************************************************
 *
 * Note: This software is released under dual MIT and GPL licenses. A
 * recipient may use this file under the terms of either the MIT license or
 * GPL License. If you wish to use only one license not the other, you can
 * indicate your decision by deleting one of the above license notices in your
 * version of this file.
 *
 *****************************************************************************/

#ifndef __VISP_DMSC_H__
#define __VISP_DMSC_H__

#include "visp_ctrl.h"

#define VISP_CID_DMSC_ENABLE (VISP_CID_DMSC_BASE + 0x0000)
#define VISP_CID_DMSC_CAC_ENABLE (VISP_CID_DMSC_BASE + 0x0001)
#define VISP_CID_DMSC_DEMOIRE_ENABLE (VISP_CID_DMSC_BASE + 0x0002)
#define VISP_CID_DMSC_DEPURPLE_ENABLE (VISP_CID_DMSC_BASE + 0x0003)
#define VISP_CID_DMSC_SHARPEN_ENABLE (VISP_CID_DMSC_BASE + 0x0004)
#define VISP_CID_DMSC_SHARPEN_LINE_ENABLE (VISP_CID_DMSC_BASE + 0x0005)
#define VISP_CID_DMSC_DEFALSE_ENABLE (VISP_CID_DMSC_BASE + 0x0006)
#define VISP_CID_DMSC_INTERP_CORNER_ENABLE (VISP_CID_DMSC_BASE + 0x0007)
#define VISP_CID_DMSC_DECLINE_ENABLE (VISP_CID_DMSC_BASE + 0x0008)
#define VISP_CID_DMSC_RESET (VISP_CID_DMSC_BASE + 0x0009)
#define VISP_CID_DMSC_MODE (VISP_CID_DMSC_BASE + 0x000A)
#define VISP_CID_DMSC_AUTO_LEVEL (VISP_CID_DMSC_BASE + 0x000B)
#define VISP_CID_DMSC_AUTO_GAIN (VISP_CID_DMSC_BASE + 0x000C)
#define VISP_CID_DMSC_AUTO_INTERP_DIR_STRENGTH (VISP_CID_DMSC_BASE + 0x000D)
#define VISP_CID_DMSC_AUTO_INTERP_LARGE_STRENGTH (VISP_CID_DMSC_BASE + 0x000E)
#define VISP_CID_DMSC_AUTO_DECLINE_ENABLE (VISP_CID_DMSC_BASE + 0x000F)
#define VISP_CID_DMSC_AUTO_HIGH_LIGHT_THRESHOLD (VISP_CID_DMSC_BASE + 0x0010)
#define VISP_CID_DMSC_AUTO_DEPURPLE_ENABLE (VISP_CID_DMSC_BASE + 0x0011)
#define VISP_CID_DMSC_AUTO_DEPURPLE_THRESHOLD (VISP_CID_DMSC_BASE + 0x0012)
#define VISP_CID_DMSC_AUTO_DEPURPLE_SAT_SHRINK (VISP_CID_DMSC_BASE + 0x0013)
#define VISP_CID_DMSC_AUTO_DEPURPLE_CBCR_RANGE (VISP_CID_DMSC_BASE + 0x0014)
#define VISP_CID_DMSC_AUTO_DENOISE_STRENGTH (VISP_CID_DMSC_BASE + 0x0015)
#define VISP_CID_DMSC_AUTO_SHARPEN_ENABLE (VISP_CID_DMSC_BASE + 0x0016)
#define VISP_CID_DMSC_AUTO_SHARPEN_FACTOR (VISP_CID_DMSC_BASE + 0x0017)
#define VISP_CID_DMSC_AUTO_SHARPEN_CLIP (VISP_CID_DMSC_BASE + 0x0018)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE0_T1 (VISP_CID_DMSC_BASE + 0x0019)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE0_T2_SHIFT (VISP_CID_DMSC_BASE + 0x001A)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE0_T3 (VISP_CID_DMSC_BASE + 0x001B)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE0_T4_SHIFT (VISP_CID_DMSC_BASE + 0x001C)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE0_R1 (VISP_CID_DMSC_BASE + 0x001D)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE0_R2 (VISP_CID_DMSC_BASE + 0x001E)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE0_R3 (VISP_CID_DMSC_BASE + 0x001F)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE1_T1 (VISP_CID_DMSC_BASE + 0x0020)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE1_T2_SHIFT (VISP_CID_DMSC_BASE + 0x0021)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE1_T3 (VISP_CID_DMSC_BASE + 0x0022)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE1_T4_SHIFT (VISP_CID_DMSC_BASE + 0x0023)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE1_R1 (VISP_CID_DMSC_BASE + 0x0024)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE1_R2 (VISP_CID_DMSC_BASE + 0x0025)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE1_R3 (VISP_CID_DMSC_BASE + 0x0026)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE2_T1 (VISP_CID_DMSC_BASE + 0x0027)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE2_T2_SHIFT (VISP_CID_DMSC_BASE + 0x0028)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE2_T3 (VISP_CID_DMSC_BASE + 0x0029)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE2_T4_SHIFT (VISP_CID_DMSC_BASE + 0x002A)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE2_R1 (VISP_CID_DMSC_BASE + 0x002B)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE2_R2 (VISP_CID_DMSC_BASE + 0x002C)
#define VISP_CID_DMSC_AUTO_SHARPEN_CURVE2_R3 (VISP_CID_DMSC_BASE + 0x002D)
#define VISP_CID_DMSC_MANU_GRAD_THR_MIN (VISP_CID_DMSC_BASE + 0x002E)
#define VISP_CID_DMSC_MANU_GRAD_THR_MAX (VISP_CID_DMSC_BASE + 0x002F)
#define VISP_CID_DMSC_MANU_DIFF_COLOR_COEF (VISP_CID_DMSC_BASE + 0x0030)
#define VISP_CID_DMSC_MANU_ADAP_COEF_MODE (VISP_CID_DMSC_BASE + 0x0031)
#define VISP_CID_DMSC_MANU_ADAP_COEF_THR_LOW (VISP_CID_DMSC_BASE + 0x0032)
#define VISP_CID_DMSC_MANU_ADAP_COEF_THR_SHIFT (VISP_CID_DMSC_BASE + 0x0033)
#define VISP_CID_DMSC_MANU_ADAP_COEF_MIN (VISP_CID_DMSC_BASE + 0x0034)
#define VISP_CID_DMSC_MANU_ADAP_COEF_MAX (VISP_CID_DMSC_BASE + 0x0035)
#define VISP_CID_DMSC_MANU_HIGH_LIGH_CONTROL_THR (VISP_CID_DMSC_BASE + 0x0036)
#define VISP_CID_DMSC_MANU_HIGH_LIGH_CONTROL_STRENGTH \
	(VISP_CID_DMSC_BASE + 0x0037)
#define VISP_CID_DMSC_MANU_DEBURST_MODE (VISP_CID_DMSC_BASE + 0x0038)
#define VISP_CID_DMSC_MANU_PURE_G_WEIGHT (VISP_CID_DMSC_BASE + 0x0039)
#define VISP_CID_DMSC_MANU_PURE_RB_WEIGHT (VISP_CID_DMSC_BASE + 0x003A)
#define VISP_CID_DMSC_MANU_PURE_G_WEIGHT_ISO (VISP_CID_DMSC_BASE + 0x003B)
#define VISP_CID_DMSC_MANU_PURE_RB_WEIGHT_ISO (VISP_CID_DMSC_BASE + 0x003C)
#define VISP_CID_DMSC_MANU_CAC_A_BLUE (VISP_CID_DMSC_BASE + 0x003D)
#define VISP_CID_DMSC_MANU_CAC_A_RED (VISP_CID_DMSC_BASE + 0x003E)
#define VISP_CID_DMSC_MANU_CAC_B_BLUE (VISP_CID_DMSC_BASE + 0x003F)
#define VISP_CID_DMSC_MANU_CAC_B_RED (VISP_CID_DMSC_BASE + 0x0040)
#define VISP_CID_DMSC_MANU_CAC_C_BLUE (VISP_CID_DMSC_BASE + 0x0041)
#define VISP_CID_DMSC_MANU_CAC_C_RED (VISP_CID_DMSC_BASE + 0x0042)
#define VISP_CID_DMSC_MANU_CAC_CENTER_H_OFFSET (VISP_CID_DMSC_BASE + 0x0043)
#define VISP_CID_DMSC_MANU_CAC_CENTER_V_OFFSET (VISP_CID_DMSC_BASE + 0x0044)
#define VISP_CID_DMSC_MANU_DEMOIRE_REFINE_G_THR (VISP_CID_DMSC_BASE + 0x0045)
#define VISP_CID_DMSC_MANU_SHARPEN_LINE_STRENGTH (VISP_CID_DMSC_BASE + 0x0046)
#define VISP_CID_DMSC_MANU_SHARPEN_LINE_T1 (VISP_CID_DMSC_BASE + 0x0047)
#define VISP_CID_DMSC_MANU_SHARPEN_LINE_SHIFT1 (VISP_CID_DMSC_BASE + 0x0048)
#define VISP_CID_DMSC_MANU_SHARPEN_LINE_R1 (VISP_CID_DMSC_BASE + 0x0049)
#define VISP_CID_DMSC_MANU_SHARPEN_LINE_R2 (VISP_CID_DMSC_BASE + 0x004A)
#define VISP_CID_DMSC_MANU_SHARPEN_DENOISE_STRENGTH \
	(VISP_CID_DMSC_BASE + 0x004B)
#define VISP_CID_DMSC_MANU_SHARPEN_FACTOR_WHITE (VISP_CID_DMSC_BASE + 0x004C)
#define VISP_CID_DMSC_MANU_SHARPEN_FACTOR_BLACK (VISP_CID_DMSC_BASE + 0x004D)
#define VISP_CID_DMSC_MANU_SHARPEN_CLIP_WHITE (VISP_CID_DMSC_BASE + 0x004E)
#define VISP_CID_DMSC_MANU_SHARPEN_CLIP_BLACK (VISP_CID_DMSC_BASE + 0x004F)
#define VISP_CID_DMSC_MANU_SHARPEN_CURVE_T1 (VISP_CID_DMSC_BASE + 0x0050)
#define VISP_CID_DMSC_MANU_SHARPEN_CURVE_T2_SHIFT (VISP_CID_DMSC_BASE + 0x0051)
#define VISP_CID_DMSC_MANU_SHARPEN_CURVE_T3 (VISP_CID_DMSC_BASE + 0x0052)
#define VISP_CID_DMSC_MANU_SHARPEN_CURVE_T4_SHIFT (VISP_CID_DMSC_BASE + 0x0053)
#define VISP_CID_DMSC_MANU_SHARPEN_CURVE_R1 (VISP_CID_DMSC_BASE + 0x0054)
#define VISP_CID_DMSC_MANU_SHARPEN_CURVE_R2 (VISP_CID_DMSC_BASE + 0x0055)
#define VISP_CID_DMSC_MANU_SHARPEN_CURVE_R3 (VISP_CID_DMSC_BASE + 0x0056)
#define VISP_CID_DMSC_MANU_DEFALSE_COLOR_STRENGTH (VISP_CID_DMSC_BASE + 0x0057)
#define VISP_CID_DMSC_MANU_DEFALSE_CBCR_CLASS_THR (VISP_CID_DMSC_BASE + 0x0058)
#define VISP_CID_DMSC_MANU_DEFALSE_GRAY_PROTECT_STRENGTH \
	(VISP_CID_DMSC_BASE + 0x0059)
#define VISP_CID_DMSC_MANU_DEPURPLE_GRAD_CONTROL (VISP_CID_DMSC_BASE + 0x005A)
#define VISP_CID_DMSC_MANU_DEPURPLE_PROTECT_THR_LOW \
	(VISP_CID_DMSC_BASE + 0x005B)
#define VISP_CID_DMSC_MANU_DEPURPLE_PROTECT_SHIFT (VISP_CID_DMSC_BASE + 0x005C)
#define VISP_CID_DMSC_MANU_DEPURPLE_THR (VISP_CID_DMSC_BASE + 0x005D)
#define VISP_CID_DMSC_MANU_DEPURPLE_CBCR_MODE (VISP_CID_DMSC_BASE + 0x005E)
#define VISP_CID_DMSC_MANU_DEPURPLE_SAT_SHRINK (VISP_CID_DMSC_BASE + 0x005F)
#define VISP_CID_DMSC_MANU_DEPURPLE_COLOR_RANGE_MODE \
	(VISP_CID_DMSC_BASE + 0x0060)
#define VISP_CID_DMSC_MANU_DEPURPLE_CB_LOW_THR (VISP_CID_DMSC_BASE + 0x0061)
#define VISP_CID_DMSC_MANU_DEPURPLE_CB_HIGH_THR (VISP_CID_DMSC_BASE + 0x0062)
#define VISP_CID_DMSC_MANU_DEPURPLE_CR_LOW_THR (VISP_CID_DMSC_BASE + 0x0063)
#define VISP_CID_DMSC_MANU_DEPURPLE_CR_HIGH_THR (VISP_CID_DMSC_BASE + 0x0064)
#define VISP_CID_DMSC_MANU_INTERP_CORNER_DIR_STRENGTH \
	(VISP_CID_DMSC_BASE + 0x0065)
#define VISP_CID_DMSC_MANU_INTERP_CORNER_LARGE_STRENGTH \
	(VISP_CID_DMSC_BASE + 0x0066)
#define VISP_CID_DMSC_MANU_INTERP_CORNER_DIR0_INTERP_TYPE \
	(VISP_CID_DMSC_BASE + 0x0067)
#define VISP_CID_DMSC_MANU_DECLINE_CORNER_LOW_THR (VISP_CID_DMSC_BASE + 0x0068)
#define VISP_CID_DMSC_MANU_DECLINE_CORNER_SHIFT (VISP_CID_DMSC_BASE + 0x0069)
#define VISP_CID_DMSC_STAT_GRAD_THR_MIN (VISP_CID_DMSC_BASE + 0x006A)
#define VISP_CID_DMSC_STAT_GRAD_THR_MAX (VISP_CID_DMSC_BASE + 0x006B)
#define VISP_CID_DMSC_STAT_DIFF_COLOR_COEF (VISP_CID_DMSC_BASE + 0x006C)
#define VISP_CID_DMSC_STAT_ADAP_COEF_MODE (VISP_CID_DMSC_BASE + 0x006D)
#define VISP_CID_DMSC_STAT_ADAP_COEF_THR_LOW (VISP_CID_DMSC_BASE + 0x006E)
#define VISP_CID_DMSC_STAT_ADAP_COEF_THR_SHIFT (VISP_CID_DMSC_BASE + 0x006F)
#define VISP_CID_DMSC_STAT_ADAP_COEF_MIN (VISP_CID_DMSC_BASE + 0x0070)
#define VISP_CID_DMSC_STAT_ADAP_COEF_MAX (VISP_CID_DMSC_BASE + 0x0071)
#define VISP_CID_DMSC_STAT_HIGH_LIGH_CONTROL_THR (VISP_CID_DMSC_BASE + 0x0072)
#define VISP_CID_DMSC_STAT_HIGH_LIGH_CONTROL_STRENGTH \
	(VISP_CID_DMSC_BASE + 0x0073)
#define VISP_CID_DMSC_STAT_DEBURST_MODE (VISP_CID_DMSC_BASE + 0x0074)
#define VISP_CID_DMSC_STAT_PURE_G_WEIGHT (VISP_CID_DMSC_BASE + 0x0075)
#define VISP_CID_DMSC_STAT_PURE_RB_WEIGHT (VISP_CID_DMSC_BASE + 0x0076)
#define VISP_CID_DMSC_STAT_PURE_G_WEIGHT_ISO (VISP_CID_DMSC_BASE + 0x0077)
#define VISP_CID_DMSC_STAT_PURE_RB_WEIGHT_ISO (VISP_CID_DMSC_BASE + 0x0078)
#define VISP_CID_DMSC_STAT_CAC_A_BLUE (VISP_CID_DMSC_BASE + 0x0079)
#define VISP_CID_DMSC_STAT_CAC_A_RED (VISP_CID_DMSC_BASE + 0x007A)
#define VISP_CID_DMSC_STAT_CAC_B_BLUE (VISP_CID_DMSC_BASE + 0x007B)
#define VISP_CID_DMSC_STAT_CAC_B_RED (VISP_CID_DMSC_BASE + 0x007C)
#define VISP_CID_DMSC_STAT_CAC_C_BLUE (VISP_CID_DMSC_BASE + 0x007D)
#define VISP_CID_DMSC_STAT_CAC_C_RED (VISP_CID_DMSC_BASE + 0x007E)
#define VISP_CID_DMSC_STAT_CAC_CENTER_H_OFFSET (VISP_CID_DMSC_BASE + 0x007F)
#define VISP_CID_DMSC_STAT_CAC_CENTER_V_OFFSET (VISP_CID_DMSC_BASE + 0x0080)
#define VISP_CID_DMSC_STAT_DEMOIRE_REFINE_G_THR (VISP_CID_DMSC_BASE + 0x0081)
#define VISP_CID_DMSC_STAT_SHARPEN_LINE_STRENGTH (VISP_CID_DMSC_BASE + 0x0082)
#define VISP_CID_DMSC_STAT_SHARPEN_LINE_T1 (VISP_CID_DMSC_BASE + 0x0083)
#define VISP_CID_DMSC_STAT_SHARPEN_LINE_SHIFT1 (VISP_CID_DMSC_BASE + 0x0084)
#define VISP_CID_DMSC_STAT_SHARPEN_LINE_R1 (VISP_CID_DMSC_BASE + 0x0085)
#define VISP_CID_DMSC_STAT_SHARPEN_LINE_R2 (VISP_CID_DMSC_BASE + 0x0086)
#define VISP_CID_DMSC_STAT_SHARPEN_DENOISE_STRENGTH \
	(VISP_CID_DMSC_BASE + 0x0087)
#define VISP_CID_DMSC_STAT_SHARPEN_FACTOR_WHITE (VISP_CID_DMSC_BASE + 0x0088)
#define VISP_CID_DMSC_STAT_SHARPEN_FACTOR_BLACK (VISP_CID_DMSC_BASE + 0x0089)
#define VISP_CID_DMSC_STAT_SHARPEN_CLIP_WHITE (VISP_CID_DMSC_BASE + 0x008A)
#define VISP_CID_DMSC_STAT_SHARPEN_CLIP_BLACK (VISP_CID_DMSC_BASE + 0x008B)
#define VISP_CID_DMSC_STAT_SHARPEN_CURVE_T1 (VISP_CID_DMSC_BASE + 0x008C)
#define VISP_CID_DMSC_STAT_SHARPEN_CURVE_T2_SHIFT (VISP_CID_DMSC_BASE + 0x008D)
#define VISP_CID_DMSC_STAT_SHARPEN_CURVE_T3 (VISP_CID_DMSC_BASE + 0x008E)
#define VISP_CID_DMSC_STAT_SHARPEN_CURVE_T4_SHIFT (VISP_CID_DMSC_BASE + 0x008F)
#define VISP_CID_DMSC_STAT_SHARPEN_CURVE_R1 (VISP_CID_DMSC_BASE + 0x0090)
#define VISP_CID_DMSC_STAT_SHARPEN_CURVE_R2 (VISP_CID_DMSC_BASE + 0x0091)
#define VISP_CID_DMSC_STAT_SHARPEN_CURVE_R3 (VISP_CID_DMSC_BASE + 0x0092)
#define VISP_CID_DMSC_STAT_DEFALSE_COLOR_STRENGTH (VISP_CID_DMSC_BASE + 0x0093)
#define VISP_CID_DMSC_STAT_DEFALSE_CBCR_CLASS_THR (VISP_CID_DMSC_BASE + 0x0094)
#define VISP_CID_DMSC_STAT_DEFALSE_GRAY_PROTECT_STRENGTH \
	(VISP_CID_DMSC_BASE + 0x0095)
#define VISP_CID_DMSC_STAT_DEPURPLE_GRAD_CONTROL (VISP_CID_DMSC_BASE + 0x0096)
#define VISP_CID_DMSC_STAT_DEPURPLE_PROTECT_THR_LOW \
	(VISP_CID_DMSC_BASE + 0x0097)
#define VISP_CID_DMSC_STAT_DEPURPLE_PROTECT_SHIFT (VISP_CID_DMSC_BASE + 0x0098)
#define VISP_CID_DMSC_STAT_DEPURPLE_THR (VISP_CID_DMSC_BASE + 0x0099)
#define VISP_CID_DMSC_STAT_DEPURPLE_CBCR_MODE (VISP_CID_DMSC_BASE + 0x009A)
#define VISP_CID_DMSC_STAT_DEPURPLE_SAT_SHRINK (VISP_CID_DMSC_BASE + 0x009B)
#define VISP_CID_DMSC_STAT_DEPURPLE_COLOR_RANGE_MODE \
	(VISP_CID_DMSC_BASE + 0x009C)
#define VISP_CID_DMSC_STAT_DEPURPLE_CB_LOW_THR (VISP_CID_DMSC_BASE + 0x009D)
#define VISP_CID_DMSC_STAT_DEPURPLE_CB_HIGH_THR (VISP_CID_DMSC_BASE + 0x009E)
#define VISP_CID_DMSC_STAT_DEPURPLE_CR_LOW_THR (VISP_CID_DMSC_BASE + 0x009F)
#define VISP_CID_DMSC_STAT_DEPURPLE_CR_HIGH_THR (VISP_CID_DMSC_BASE + 0x00A0)
#define VISP_CID_DMSC_STAT_INTERP_CORNER_DIR_STRENGTH \
	(VISP_CID_DMSC_BASE + 0x00A1)
#define VISP_CID_DMSC_STAT_INTERP_CORNER_LARGE_STRENGTH \
	(VISP_CID_DMSC_BASE + 0x00A2)
#define VISP_CID_DMSC_STAT_INTERP_CORNER_DIR0_INTERP_TYPE \
	(VISP_CID_DMSC_BASE + 0x00A3)
#define VISP_CID_DMSC_STAT_DECLINE_CORNER_LOW_THR (VISP_CID_DMSC_BASE + 0x00A4)
#define VISP_CID_DMSC_STAT_DECLINE_CORNER_SHIFT (VISP_CID_DMSC_BASE + 0x00A5)

#ifdef __KERNEL__
int visp_dmsc_ctrl_count(void);
int visp_dmsc_ctrl_create(struct visp_dev *isp_dev);
#endif

#endif
