/****************************************************************************
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2025 VeriSilicon Holdings Co., Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *****************************************************************************
 *
 * The GPL License (GPL)
 *
 * Copyright (c) 2025 VeriSilicon Holdings Co., Ltd.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program;
 *
 *****************************************************************************
 *
 * Note: This software is released under dual MIT and GPL licenses. A
 * recipient may use this file under the terms of either the MIT license or
 * GPL License. If you wish to use only one license not the other, you can
 * indicate your decision by deleting one of the above license notices in your
 * version of this file.
 *
 *****************************************************************************/
 
 #ifndef __MAILBOX_CMD_H__
#define __MAILBOX_CMD_H__

#if 0
typedef enum MBCmdId_S
{
	MB_CMD_RES_SUCCESS,
	MB_CMD_GET_SUCCESS,
	/*---------------------------------------API CMD------------------------------------*/
	APU_2_RPU_MB_CMD_CREATE_INSTANCE,
	APU_2_RPU_MB_CMD_DESTORY,
	APU_2_RPU_MB_CMD_LOAD_CALIBRATION,
	APU_2_RPU_MB_CMD_SET_OUT_FORMAT,
	APU_2_RPU_MB_CMD_SET_IN_FORMAT,
	APU_2_RPU_MB_CMD_GET_OUT_FORMAT,
	APU_2_RPU_MB_CMD_GET_IN_FORMAT,
	APU_2_RPU_MB_CMD_SET_ISP_WINDOW,
	APU_2_RPU_MB_CMD_GET_ISP_WINDOW,
	APU_2_RPU_MB_CMD_CONNECT_CAMERA,
	APU_2_RPU_MB_CMD_DISCONNECT_CAMERA,
	APU_2_RPU_MB_CMD_START_STREAMING,
	APU_2_RPU_MB_CMD_STOP_STREAMING,
	APU_2_RPU_MB_CMD_SET_PATH_STREAMING,
	APU_2_RPU_MB_CMD_GET_PATH_STREAMING,
	APU_2_RPU_MB_CMD_ALLOC_RES_MEMORY,
	APU_2_RPU_MB_CMD_FREE_RES_MEMORY,
	APU_2_RPU_MB_CMD_WRITE_REGISTER,
	APU_2_RPU_MB_CMD_READ_REGISTER,
	APU_2_RPU_MB_CMD_IMAGE_SET_METADATA,
	APU_2_RPU_MB_CMD_NrRelocEnable,
	APU_2_RPU_MB_CMD_NrRelocDisable,

/*--------------------------------------Buffer API CMD----------------------------------*/
	APU_2_RPU_MB_CMD_INIT_BUF_CHAIN,
	APU_2_RPU_MB_CMD_DEINIT_BUF_CHAIN,
	APU_2_RPU_MB_CMD_GET_BUFFER_SIZE,
	APU_2_RPU_MB_CMD_CREATE_BUFFER_POOL,
	APU_2_RPU_MB_CMD_DESTORY_BUFFER_POOL,
	APU_2_RPU_MB_CMD_SETUP_BUF_MGMT,
	APU_2_RPU_MB_CMD_RELEASE_BUF_MGMT,
	APU_2_RPU_MB_CMD_DEQUE_BUFFER,
	APU_2_RPU_MB_CMD_ENQUE_BUFFER,

/*----------------------------------------SENSOR API-------------------------------------*/
	APU_2_RPU_MB_CMD_SENSOR_OPEN,
	APU_2_RPU_MB_CMD_SENSOR_DRV_HANDLE_REG,
	APU_2_RPU_MB_CMD_SENSOR_DRV_HANDLE_UNREG,
	APU_2_RPU_MB_CMD_SENSOR_CLOSE,
	APU_2_RPU_MB_CMD_SENSOR_MAPPING,
	APU_2_RPU_MB_CMD_SENSOR_QUERY,
	APU_2_RPU_MB_CMD_SENSOR_GET_INFO,
	APU_2_RPU_MB_CMD_SENSOR_SET_TP,  // TEST PATTERN
	APU_2_RPU_MB_CMD_SENSOR_SET_REG,
	APU_2_RPU_MB_CMD_SENSOR_GET_REG,
	APU_2_RPU_MB_CMD_SENSOR_SET_FRAMERATE,
	APU_2_RPU_MB_CMD_SENSOR_GET_FRAMERATE,
	APU_2_RPU_MB_CMD_SENSOR_GET_MODE_INFO,
	APU_2_RPU_MB_CMD_SENSOR_GET_STATUS,
	APU_2_RPU_MB_CMD_SENSOR_SET_GAIN,
	APU_2_RPU_MB_CMD_SENSOR_GET_GAIN,
	APU_2_RPU_MB_CMD_SENSOR_SET_EXP_CTL,
	APU_2_RPU_MB_CMD_SENSOR_GET_EXP_CTL,
	APU_2_RPU_MB_CMD_SENSOR_SetFocusPositon,
	APU_2_RPU_MB_CMD_SENSOR_GetFocusPositon,
	APU_2_RPU_MB_CMD_SENSOR_SET_STREAMING,
	APU_2_RPU_MB_CMD_SENSOR_GET_OPT_INFO,
	APU_2_RPU_MB_CMD_SENSOR_GET_METADATA_ATTR,
	APU_2_RPU_MB_CMD_SENSOR_SET_METADATA_ATTR,
	APU_2_RPU_MB_CMD_SENSOR_GET_METADATA_WIN,

/*----------------------------------------FUSA API----------------------------------------*/
	APU_2_RPU_MB_CMD_Fusa_FaultInject_Enable,
	APU_2_RPU_MB_CMD_Fusa_Ecc_Enable,
	APU_2_RPU_MB_CMD_Fusa_Ecc_Disable,
	APU_2_RPU_MB_CMD_Fusa_Pixel_Count_Enable,
	APU_2_RPU_MB_CMD_Fusa_Pixel_Count_Disable,
	APU_2_RPU_MB_CMD_SET_Fusa_Pixel_Count,
	APU_2_RPU_MB_CMD_GET_Fusa_Pixel_Count,
	APU_2_RPU_MB_CMD_Fusa_Timeout_Enable,
	APU_2_RPU_MB_CMD_Fusa_Timeout_Disable,
	APU_2_RPU_MB_CMD_Fusa_Bist_Enable,
	APU_2_RPU_MB_CMD_Fusa_Bist_Disable,
	APU_2_RPU_MB_CMD_Fusa_Bist_Power_Up_Enable,
	APU_2_RPU_MB_CMD_Fusa_Crc_Enable,
	APU_2_RPU_MB_CMD_Fusa_Crc_Disable,
	APU_2_RPU_MB_CMD_SET_Fusa_Crc,
	APU_2_RPU_MB_CMD_GET_Fusa_Crc,
	APU_2_RPU_MB_CMD_GET_Fusa_Bist,
	APU_2_RPU_MB_CMD_Fusa_Register_EventCb,
	APU_2_RPU_MB_CMD_Fusa_RESET,
	APU_2_RPU_MB_CMD_Fusa_GET_VERSION,

/*----------------------------------------VI200 API----------------------------------------*/
	APU_2_RPU_MB_CMD_SetAdapterCfg,
	APU_2_RPU_MB_CMD_GetAdapterCfg,
	APU_2_RPU_MB_CMD_Vi200GetStatus,
	APU_2_RPU_MB_CMD_Vi200Reset,
	APU_2_RPU_MB_CMD_Vi200GetVersion,
	APU_2_RPU_MB_CMD_Vi200HwIsEnable,

/*----------------------------------------TPG API----------------------------------------*/
	APU_2_RPU_MB_CMD_TPG_SetCfg,
	APU_2_RPU_MB_CMD_TPG_GetCfg,
	APU_2_RPU_MB_CMD_TPG_Enable,
	APU_2_RPU_MB_CMD_TPG_Disable,
	APU_2_RPU_MB_CMD_TPG_Reset,
	APU_2_RPU_MB_CMD_TPG_GetVersion,

/*---------------------------------------2DNR API V5_2-----------------------------------*/
	APU_2_RPU_MB_CMD_2DNR_ENABLE,
	APU_2_RPU_MB_CMD_2DNR_DISABLE,
	APU_2_RPU_MB_CMD_2DNR_SET_CONFIG,
	APU_2_RPU_MB_CMD_2DNR_GET_CONFIG,
	APU_2_RPU_MB_CMD_2DNR_LUMA_ENABLE,
	APU_2_RPU_MB_CMD_2DNR_LUMA_DISABLE,
	APU_2_RPU_MB_CMD_2DNR_GET_STATUS,
	APU_2_RPU_MB_CMD_2DNR_GET_VERSION,
	APU_2_RPU_MB_CMD_2DNR_RESET,

/*-----------------------------------------3DNR API V2_1-------------------------------*/
	APU_2_RPU_MB_CMD_3DNR_SET_CONFIG,
	APU_2_RPU_MB_CMD_3DNR_GET_CONFIG,
	APU_2_RPU_MB_CMD_3DNR_ENABLE,
	APU_2_RPU_MB_CMD_3DNR_DISABLE,
	APU_2_RPU_MB_CMD_3DNR_GET_STATUS,
	APU_2_RPU_MB_CMD_3DNR_RESET,
	APU_2_RPU_MB_CMD_3DNR_GET_VERSION,

/*--------------------------------------------AE API------------------------------------*/
	RPU_2_APU_MB_CMD_REGISTER_AELIB,
	RPU_2_APU_MB_CMD_UNREGISTER_AELIB,
	APU_2_RPU_MB_CMD_AE_SET_CONFIG,
	APU_2_RPU_MB_CMD_AE_GET_CONFIG,
	APU_2_RPU_MB_CMD_AE_SET_MODE,
	APU_2_RPU_MB_CMD_AE_GET_MODE,
	APU_2_RPU_MB_CMD_AE_SET_ROI,
	APU_2_RPU_MB_CMD_AE_GET_ROI,
	APU_2_RPU_MB_CMD_AE_ENABLE,
	APU_2_RPU_MB_CMD_AE_DISABLE,
	APU_2_RPU_MB_CMD_AE_RESET,
	APU_2_RPU_MB_CMD_AE_GET_STATUS,
	APU_2_RPU_MB_CMD_AE_GET_HISTOGRAM,
	APU_2_RPU_MB_CMD_AE_GET_LUMINANCE,
	APU_2_RPU_MB_CMD_AE_GET_OBJECT_REGION,
	APU_2_RPU_MB_CMD_AE_GET_VERSION,

/*--------------------------------------------AF API V1-----------------------------------*/
	APU_2_RPU_MB_CMD_AF_REGISTER,
	APU_2_RPU_MB_CMD_AF_UNREGISTER,
	APU_2_RPU_MB_CMD_AF_SET_MODE,
	APU_2_RPU_MB_CMD_AF_GET_MODE,
	APU_2_RPU_MB_CMD_AF_SET_CONFIG,
	APU_2_RPU_MB_CMD_AF_GET_CONFIG,
	APU_2_RPU_MB_CMD_AF_SET_ROI_INDEX,
	APU_2_RPU_MB_CMD_AF_GET_ROI_INDEX,
	APU_2_RPU_MB_CMD_AF_ENABLE,
	APU_2_RPU_MB_CMD_AF_DISABLE,
	APU_2_RPU_MB_CMD_AF_GET_STATUS,
	APU_2_RPU_MB_CMD_AF_GET_VERSION,
	APU_2_RPU_MB_CMD_AF_RESET,

/*--------------------------------------------AFM API -----------------------------------*/
	APU_2_RPU_MB_CMD_AFM_SET_THRESHOLD,
	APU_2_RPU_MB_CMD_AFM_GET_THRESHOLD,
	APU_2_RPU_MB_CMD_AFM_GET_STATISTICS,
	APU_2_RPU_MB_CMD_AFM_SET_MEASURE_WINDOW,
	APU_2_RPU_MB_CMD_AFM_GET_MEASURE_WINDOW,
	APU_2_RPU_MB_CMD_AFM_ENABLE,
	APU_2_RPU_MB_CMD_AFM_DISABLE,
	APU_2_RPU_MB_CMD_AFM_GET_STATUS,
	APU_2_RPU_MB_CMD_AFM_GET_VERSION,
	APU_2_RPU_MB_CMD_AFM_RESET,

/*--------------------------------------------AFM V3 API -----------------------------------*/
	APU_2_RPU_MB_CMD_AFMV3_SET_CFG,
	APU_2_RPU_MB_CMD_AFMV3_GET_CFG,
	APU_2_RPU_MB_CMD_AFMV3_GET_STATISTICS,
	APU_2_RPU_MB_CMD_AFMV3_ENABLE,
	APU_2_RPU_MB_CMD_AFMV3_DISABLE,
	APU_2_RPU_MB_CMD_AFMV3_GAMMA_ENABLE,
	APU_2_RPU_MB_CMD_AFMV3_GAMMA_DISABLE,
	APU_2_RPU_MB_CMD_AFMV3_GET_STATUS,
	APU_2_RPU_MB_CMD_AFMV3_GET_VERSION,
	APU_2_RPU_MB_CMD_AFMV3_RESET,

/*---------------------------------------------AWB API--------------------------------------*/
	APU_2_RPU_MB_CMD_REGISTER_AWB_LIB,
	APU_2_RPU_MB_CMD_UNREGISTER_AWB_LIB,
	APU_2_RPU_MB_CMD_AWB_SET_CONFIG,
	APU_2_RPU_MB_CMD_AWB_GET_CONFIG,
	APU_2_RPU_MB_CMD_AWB_SET_MODE,
	APU_2_RPU_MB_CMD_AWB_GET_MODE,
	APU_2_RPU_MB_CMD_AWB_SET_ROI,
	APU_2_RPU_MB_CMD_AWB_GET_ROI,
	APU_2_RPU_MB_CMD_AWB_ENABLE,
	APU_2_RPU_MB_CMD_AWB_DISABLE,
	APU_2_RPU_MB_CMD_AWB_GET_STATUS,
	APU_2_RPU_MB_CMD_AWB_GET_VERSION,
	APU_2_RPU_MB_CMD_AWB_GET_ColorTempWeight,

/*----------------------------------------------BLS API-----------------------------------------*/
	APU_2_RPU_MB_CMD_BLS_SET_CONFIG,
	APU_2_RPU_MB_CMD_BLS_GET_CONFIG,
	APU_2_RPU_MB_CMD_BLS_GET_STATUS,
	APU_2_RPU_MB_CMD_BLS_RESET,
	APU_2_RPU_MB_CMD_BLS_GET_VERSION,

/*----------------------------------------------CCM API-----------------------------------------*/
	APU_2_RPU_MB_CMD_CCM_ENABLE,
	APU_2_RPU_MB_CMD_CCM_DISABLE,
	APU_2_RPU_MB_CMD_CCM_SET_CONFIG,
	APU_2_RPU_MB_CMD_CCM_GET_CONFIG,
	APU_2_RPU_MB_CMD_CCM_GET_STATUS,
	APU_2_RPU_MB_CMD_CCM_RESET,
	APU_2_RPU_MB_CMD_CCM_GET_VERSION,

/*-----------------------------------------------CPD API----------------------------------------*/
	APU_2_RPU_MB_CMD_CPD_SET_CONFIG,
	APU_2_RPU_MB_CMD_CPD_GET_CONFIG,
	APU_2_RPU_MB_CMD_CPD_EXPAND_ENABLE,
	APU_2_RPU_MB_CMD_CPD_EXPAND_DISABLE,
	APU_2_RPU_MB_CMD_CPD_EXPAND_GET_STATUS,
	APU_2_RPU_MB_CMD_CPD_COMPRESS_GET_STATUS,
	APU_2_RPU_MB_CMD_CPD_RESET,
	APU_2_RPU_MB_CMD_CPD_GET_VERSION,

/*-----------------------------------------------CPROC API---------------------------------------*/
	APU_2_RPU_MB_CMD_CPROC_SET_CONFIG,
	APU_2_RPU_MB_CMD_CPROC_GET_CONFIG,
	APU_2_RPU_MB_CMD_CPROC_SET_RANGE,
	APU_2_RPU_MB_CMD_CPROC_GET_RANGE,
	APU_2_RPU_MB_CMD_CPROC_ENABLE,
	APU_2_RPU_MB_CMD_CPROC_DISABLE,
	APU_2_RPU_MB_CMD_CPROC_GET_STATUS,
	APU_2_RPU_MB_CMD_CPROC_RESET,
	APU_2_RPU_MB_CMD_CPROC_GET_VERSION,

/*---------------------------------------------DG API-----------------------------------------------*/
	APU_2_RPU_MB_CMD_DG_SET_CONFIG,
	APU_2_RPU_MB_CMD_DG_GET_CONFIG,
	APU_2_RPU_MB_CMD_DG_ENABLE,
	APU_2_RPU_MB_CMD_DG_DISABLE,
	APU_2_RPU_MB_CMD_DG_GET_STATUS,
	APU_2_RPU_MB_CMD_DG_RESET,
	APU_2_RPU_MB_CMD_DG_GET_VERSION,

/*--------------------------------------------DMSC API--------------------------------------------*/
	APU_2_RPU_MB_CMD_DMSC_SET_CONFIG,
	APU_2_RPU_MB_CMD_DMSC_GET_CONFIG,
	APU_2_RPU_MB_CMD_DMSC_ENABLE,
	APU_2_RPU_MB_CMD_DMSC_DISABLE,
	APU_2_RPU_MB_CMD_DMSC_CAC_ENABLE,
	APU_2_RPU_MB_CMD_DMSC_CAC_DISABLE,
	APU_2_RPU_MB_CMD_DMSC_DEMOIRE_ENABLE,
	APU_2_RPU_MB_CMD_DMSC_DEMOIRE_DISABLE,
	APU_2_RPU_MB_CMD_DMSC_DEPURPLE_ENABLE,
	APU_2_RPU_MB_CMD_DMSC_DEPURPLE_DISABLE,
	APU_2_RPU_MB_CMD_DMSC_SHARPEN_ENABLE,
	APU_2_RPU_MB_CMD_DMSC_SHARPEN_DISABLE,
	APU_2_RPU_MB_CMD_DMSC_SHARPEN_LINE_ENABLE,
	APU_2_RPU_MB_CMD_DMSC_SHARPEN_LINE_DISABLE,
	APU_2_RPU_MB_CMD_DMSC_SKIN_ENABLE,
	APU_2_RPU_MB_CMD_DMSC_SKIN_DISABLE,
	APU_2_RPU_MB_CMD_DMSC_GET_STATUS,
	APU_2_RPU_MB_CMD_DMSC_RESET,
	APU_2_RPU_MB_CMD_DMSC_GET_VERSION,

/*--------------------------------------------DPCC API------------------------------------------*/
	APU_2_RPU_MB_CMD_DPCC_SET_CONFIG,
	APU_2_RPU_MB_CMD_DPCC_GET_CONFIG,
	APU_2_RPU_MB_CMD_DPCC_ENABLE,
	APU_2_RPU_MB_CMD_DPCC_DISABLE,
	APU_2_RPU_MB_CMD_DPCC_GET_STATUS,
	APU_2_RPU_MB_CMD_DPCC_RESET,
	APU_2_RPU_MB_CMD_DPCC_GET_VERSION,

/*---------------------------------------------EE API-------------------------------------------*/
	APU_2_RPU_MB_CMD_EE_SET_CONFIG,
	APU_2_RPU_MB_CMD_EE_GET_CONFIG,
	APU_2_RPU_MB_CMD_EE_ENABLE,
	APU_2_RPU_MB_CMD_EE_DISABLE,
	APU_2_RPU_MB_CMD_EE_CURVE_ENABLE,
	APU_2_RPU_MB_CMD_EE_CURVE_DISABLE,
	APU_2_RPU_MB_CMD_EE_CA_ENABLE,
	APU_2_RPU_MB_CMD_EE_CA_DISABLE,
	APU_2_RPU_MB_CMD_EE_DCI_ENABLE,
	APU_2_RPU_MB_CMD_EE_DCI_DISABLE,
	APU_2_RPU_MB_CMD_EE_GET_STATUS,
	APU_2_RPU_MB_CMD_EE_RESET,
	APU_2_RPU_MB_CMD_EE_GET_VERSION,

/*-----------------------------------------------EXP V2 API----------------------------------------*/
	APU_2_RPU_MB_CMD_EXP_V2_SET_CONFIG,
	APU_2_RPU_MB_CMD_EXP_V2_GET_CONFIG,
	APU_2_RPU_MB_CMD_EXP_V2_ENABLE,
	APU_2_RPU_MB_CMD_EXP_V2_DISABLE,
	APU_2_RPU_MB_CMD_EXP_V2_SET_MEASURE_WINDOW,
	APU_2_RPU_MB_CMD_EXP_V2_GET_MEASURE_WINDOW,
	APU_2_RPU_MB_CMD_EXP_V2_GET_STATISTICS,
	APU_2_RPU_MB_CMD_EXP_V2_GET_STATUS,
	APU_2_RPU_MB_CMD_EXP_V2_GET_VERSION,
	APU_2_RPU_MB_CMD_EXP_V2_RESET,

/*-----------------------------------------------EXP V3 API----------------------------------------*/
	APU_2_RPU_MB_CMD_EXP_V3_SET_CONFIG,
	APU_2_RPU_MB_CMD_EXP_V3_GET_CONFIG,
	APU_2_RPU_MB_CMD_EXP_V3_ENABLE,
	APU_2_RPU_MB_CMD_EXP_V3_DISABLE,
	APU_2_RPU_MB_CMD_EXP_V3_SET_MEASURE_WINDOW,
	APU_2_RPU_MB_CMD_EXP_V3_GET_MEASURE_WINDOW,
	APU_2_RPU_MB_CMD_EXP_V3_GET_STATISTICS,
	APU_2_RPU_MB_CMD_EXP_V3_GET_STATUS,
	APU_2_RPU_MB_CMD_EXP_V3_GET_VERSION,
	APU_2_RPU_MB_CMD_EXP_V3_RESET,

/*-----------------------------------------------FLEXA API----------------------------------------*/
	APU_2_RPU_MB_CMD_FLEXA_SBI_MI_SET_CONFIG,
	APU_2_RPU_MB_CMD_FLEXA_SBI_MI_GET_CONFIG,

/*----------------------------------------------GC API------------------------------------------*/
	APU_2_RPU_MB_CMD_GC_SET_CONFIG,
	APU_2_RPU_MB_CMD_GC_GET_CONFIG,
	APU_2_RPU_MB_CMD_GC_ENABLE,
	APU_2_RPU_MB_CMD_GC_DISABLE,
	APU_2_RPU_MB_CMD_GC_GET_STATUS,
	APU_2_RPU_MB_CMD_GC_RESET,
	APU_2_RPU_MB_CMD_GC_GET_VERSION,

/*-----------------------------------------------GE API-----------------------------------------*/
	APU_2_RPU_MB_CMD_GE_SET_CONFIG,
	APU_2_RPU_MB_CMD_GE_GET_CONFIG,
	APU_2_RPU_MB_CMD_GE_ENABLE,
	APU_2_RPU_MB_CMD_GE_DISABLE,
	APU_2_RPU_MB_CMD_GE_GET_STATUS,
	APU_2_RPU_MB_CMD_GE_RESET,
	APU_2_RPU_MB_CMD_GE_GET_VERSION,

/*-----------------------------------------------GTM API V_1------------------------------------*/
	APU_2_RPU_MB_CMD_GTM_SET_CONFIG,
	APU_2_RPU_MB_CMD_GTM_GET_CONFIG,
	APU_2_RPU_MB_CMD_GTM_ENABLE,
	APU_2_RPU_MB_CMD_GTM_DISABLE,
	APU_2_RPU_MB_CMD_GTM_BWC_ENABLE,
	APU_2_RPU_MB_CMD_GTM_BWC_DISABLE,
	APU_2_RPU_MB_CMD_GTM_GET_STATUS,
	APU_2_RPU_MB_CMD_GTM_GET_VERSION,
	APU_2_RPU_MB_CMD_GTM_RESET,
	APU_2_RPU_MB_CMD_GTM_GETHIST,

/*---------------------------------------------GWDR API ----------------------------------------*/
	APU_2_RPU_MB_CMD_GWDR_SET_CONFIG,
	APU_2_RPU_MB_CMD_GWDR_GET_CONFIG,
	APU_2_RPU_MB_CMD_GWDR_ENABLE,
	APU_2_RPU_MB_CMD_GWDR_DISABLE,
	APU_2_RPU_MB_CMD_GWDR_GET_STATUS,
	APU_2_RPU_MB_CMD_GWDR_RESET,
	APU_2_RPU_MB_CMD_GWDR_GET_VERSION,

/*---------------------------------------------HDR API V3_1------------------------------------*/
	APU_2_RPU_MB_CMD_HDR_SET_CONFIG,
	APU_2_RPU_MB_CMD_HDR_GET_CONFIG,
	APU_2_RPU_MB_CMD_HDR_ENABLE,
	APU_2_RPU_MB_CMD_HDR_DISABLE,
	APU_2_RPU_MB_CMD_HDR_GET_STATUS,
	APU_2_RPU_MB_CMD_HDR_RESET,
	APU_2_RPU_MB_CMD_HDR_GET_VERSION,
	APU_2_RPU_MB_CMD_HDR_SetBypassSelectEnable,

/*---------------------------------------------LSC API V3--------------------------------------*/
	APU_2_RPU_MB_CMD_LSC_SET_CONFIG,
	APU_2_RPU_MB_CMD_LSC_GET_CONFIG,
	APU_2_RPU_MB_CMD_LSC_ENABLE,
	APU_2_RPU_MB_CMD_LSC_DISABLE,
	APU_2_RPU_MB_CMD_LSC_RESET,
	APU_2_RPU_MB_CMD_LSC_GET_STATUS,
	APU_2_RPU_MB_CMD_LSC_GET_VERSION,

/*---------------------------------------------RGBIR API V2------------------------------------*/
	APU_2_RPU_MB_CMD_RGBIR_SET_INTERNAL_CONFIG,
	APU_2_RPU_MB_CMD_RGBIR_SET_CONFIG,
	APU_2_RPU_MB_CMD_RGBIR_GET_CONFIG,
	APU_2_RPU_MB_CMD_RGBIR_ENABLE,
	APU_2_RPU_MB_CMD_RGBIR_DISABLE,
	APU_2_RPU_MB_CMD_RGBIR_RCCC_ENABLE,
	APU_2_RPU_MB_CMD_RGBIR_RCCC_DISABLE,
	APU_2_RPU_MB_CMD_RGBIR_IR_RAWOUT_ENABLE,
	APU_2_RPU_MB_CMD_RGBIR_IR_RAWOUT_DISABLE,
	APU_2_RPU_MB_CMD_RGBIR_SET_OutPattern,
	APU_2_RPU_MB_CMD_RGBIR_GET_OutPattern,
	APU_2_RPU_MB_CMD_RGBIR_SET_IrPathSelect,
	APU_2_RPU_MB_CMD_RGBIR_GET_IrPathSelect,
	APU_2_RPU_MB_CMD_RGBIR_GET_STATUS,
	APU_2_RPU_MB_CMD_RGBIR_GET_VERSION,
	APU_2_RPU_MB_CMD_RGBIR_RESET,

/*-------------------------------------------WB API---------------------------*/
	APU_2_RPU_MB_CMD_WB_ENABLE,
	APU_2_RPU_MB_CMD_WB_DISABLE,
	APU_2_RPU_MB_CMD_WB_SET_CONFIG,
	APU_2_RPU_MB_CMD_WB_GET_CONFIG,
	APU_2_RPU_MB_CMD_WB_GET_STATUS,
	APU_2_RPU_MB_CMD_WB_RESET,
	APU_2_RPU_MB_CMD_WB_GET_VERSION,

/*-------------------------------------------WDR V5_2-----------------------*/
	APU_2_RPU_MB_CMD_WDR_SET_CONFIG,
	APU_2_RPU_MB_CMD_WDR_GET_CONFIG,
	APU_2_RPU_MB_CMD_WDR_ENABLE,
	APU_2_RPU_MB_CMD_WDR_DISABLE,
	APU_2_RPU_MB_CMD_WDR_HCF_ENABLE,
	APU_2_RPU_MB_CMD_WDR_HCF_DISABLE,
	APU_2_RPU_MB_CMD_WDR_GET_STATUS,
	APU_2_RPU_MB_CMD_WDR_GET_VERSION,
	APU_2_RPU_MB_CMD_WDR_RESET,

	APU_2_RPU_MB_CMB_INIT_FIRMWARE,		/**< init firmware, no command context */
	APU_2_RPU_MB_CMD_LOADCFG_STREAMING,		/**< load config from sram, no command context */
	APU_2_RPU_MB_CMD_DEINIT_STREAMING,
	RPU_2_APU_MB_CMD_REQUEST_XXXX,
	RPU_2_APU_MB_CMD_REPORT_INTERNAL_FAILURE,
	MB_CMD_RES_ERR,
	MB_CMD_RES_TIMEOUT,
	MB_CMD_END,
	MB_CMD_BUF_RET,
} MBCmdId_E;
#endif

#endif
