ISP_AE_V3 := 1
EXTRA_CFLAGS += -DISP_AE_V3

ISP_AWB_V3 := 1
EXTRA_CFLAGS += -DISP_AWB_V3

ISP_GC_V2 := 1
EXTRA_CFLAGS += -DISP_GC_V2

ISP_2DNR_V5_2 := 1
EXTRA_CFLAGS += -DISP_2DNR_V5_2

ISP_EE_V2 := 1
EXTRA_CFLAGS += -DISP_EE_V2

ISP_CPROC := 1
EXTRA_CFLAGS += -DISP_CPROC

ISP_WDR_V5_2 := 1
EXTRA_CFLAGS += -DISP_WDR_V5_2

ISP_BLS := 1
EXTRA_CFLAGS += -DISP_BLS

ISP_CCM := 1
EXTRA_CFLAGS += -DISP_CCM

ISP_DPCC := 1
EXTRA_CFLAGS += -DISP_DPCC

ISP_GE := 1
EXTRA_CFLAGS += -DISP_GE

ISP_LSC_V3 := 1
EXTRA_CFLAGS += -DISP_LSC_V3

ISP_WB_V1_1 := 1
EXTRA_CFLAGS += -DISP_WB_V1_1

ISP_DMSC_V2 := 1
EXTRA_CFLAGS += -DISP_DMSC_V2

ISP_EXP_V2 := 1
EXTRA_CFLAGS += -DISP_EXP_V2

ISP_GTM_V1 := 1
EXTRA_CFLAGS += -DISP_GTM_V1

ISP_HDR_V3_1 := 1
EXTRA_CFLAGS += -DISP_HDR_V3_1

ISP_RGBIR_V2_1 := 1
EXTRA_CFLAGS += -DISP_RGBIR_V2_1

ISP_DG_V1 := 1
EXTRA_CFLAGS += -DISP_DG_V1

ISP_CPD := 1
EXTRA_CFLAGS += -DISP_CPD
